Remove path from counter when count becomes <= 0
Upstream already behaves this way and it isn't merely an aesthetic
change. Doing this fixes an issue where count can become -1 when a new
daemon instance attempts to unmount the container base dir, with the
later not being actually mounted. The most common action leading to this
scenario is an unorderly restart of the server running docker.

After count becomes -1, a combination of "docker start" + "docker
restart" will lead to a situation in which the mountpoint is not visible
from the global namespace, and attempts to run new processes in the
container will fail with an error like this one:

error: code = 2 desc = oci runtime error: exec failed:
container_linux.go:247: starting container process caused
"process_linux.go:75: starting setns process caused \"fork/exec
/proc/self/exe: no such file or directory\""

Signed-off-by: Sergio Lopez <slp@redhat.com>